# Generated by Django 4.2.1 on 2023-06-01 19:55

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('personalinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user_auth.personalinfo')),
                ('is_customer', models.BooleanField(default=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='', validators=[django.core.validators.validate_image_file_extension])),
                ('contact', models.CharField(max_length=20, null=True, unique=True)),
            ],
            options={
                'ordering': ['-id'],
            },
            bases=('user_auth.personalinfo',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('zip_code', models.PositiveBigIntegerField()),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='user_auth.userprofile')),
            ],
            options={
                'ordering': ['individual'],
            },
        ),
    ]
