# Generated by Django 4.2.1 on 2023-06-02 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('Transfer', 'Transfer'), ('Card', 'Card'), ('Crypto', 'Crypto')], max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('completed', 'completed'), ('pending', 'pending'), ('unsuccessful', 'unsuccesful')], max_length=50),
        ),
    ]
