# Generated by Django 4.2.1 on 2023-06-06 16:56

from django.db import migrations, models
import django.db.models.deletion
import extras.funcs


class Migration(migrations.Migration):

    dependencies = [
        ('payment_management', '0002_alter_payment_payment_type_alter_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='session_id',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('Transfer', 'Transfer'), ('Card', 'Card'), ('Crypto', 'Crypto')], default=('Transfer', 'Transfer'), max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='sender',
            field=models.ForeignKey(default=django.contrib.auth.get_user, on_delete=django.db.models.deletion.CASCADE, related_name='debit', to='payment_management.wallet'),
        ),
    ]
