# Generated by Django 4.2.1 on 2023-06-08 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_management', '0004_remove_payment_payment_id_alter_payment_sender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='customer',
            new_name='owner',
        ),
    ]
