# Generated by Django 4.2.1 on 2023-06-09 09:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment_management', '0005_rename_customer_wallet_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('completed', 'completed'), ('pending', 'pending'), ('unsuccessful', 'unsuccesful')], default='pending')),
                ('time', models.DateTimeField(default=datetime.datetime(2023, 6, 9, 9, 9, 36, 452053, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.DeleteModel(
            name='Cards',
        ),
        migrations.DeleteModel(
            name='PaymentGateway',
        ),
        migrations.AddField(
            model_name='wallet',
            name='acct_number',
            field=models.BigIntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('Transfer', 'Transfer'), ('Card', 'Card'), ('Crypto', 'Crypto')], default='Transfer', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('completed', 'completed'), ('pending', 'pending'), ('unsuccessful', 'unsuccesful')], default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='transfer',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_money', to='payment_management.wallet'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_money', to='payment_management.wallet'),
        ),
    ]
