# Generated by Django 4.2.1 on 2023-06-09 09:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_management', '0006_transfer_delete_cards_delete_paymentgateway_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 9, 9, 12, 34, 162008, tzinfo=datetime.timezone.utc)),
        ),
    ]
