# Generated by Django 4.1.1 on 2023-07-12 20:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_management', '0009_alter_transfer_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='status',
            field=models.CharField(choices=[('completed', 'completed'), ('pending', 'pending'), ('unsuccessful', 'unsuccesful')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 12, 20, 6, 16, 618034, tzinfo=datetime.timezone.utc)),
        ),
    ]
