# Generated by Django 4.2.3 on 2023-07-12 21:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_management', '0010_alter_transfer_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 12, 21, 17, 5, 757080, tzinfo=datetime.timezone.utc)),
        ),
    ]
