# Generated by Django 4.2.1 on 2023-06-02 08:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderAndCart', '0002_alter_order_payment_status_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordereditem',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='ordereditem',
            name='order',
        ),
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 2, 8, 13, 30, 820610, tzinfo=datetime.timezone.utc)),
        ),
    ]
