# Generated by Django 4.2.1 on 2023-06-02 08:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderAndCart', '0004_alter_order_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 2, 8, 23, 50, 743716, tzinfo=datetime.timezone.utc)),
        ),
    ]
