# Generated by Django 4.2.1 on 2023-06-06 17:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderAndCart', '0006_alter_order_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 6, 17, 26, 28, 916676, tzinfo=datetime.timezone.utc)),
        ),
    ]
